import { ArmorClass } from "../sim/types";

export interface UnitDef {
  id: string;
  name: string;
  desc: string;
  armorClass: ArmorClass;
  hp: number;
  attack: number;
  range: number; // 0 = melee (uses contact range)
  attackInterval: number; // seconds
  armor: number;
  /** Armor vs ranged hits. Defaults to `armor` when omitted (no melee/pierce
   *  split); set it to model units that resist arrows but not blades. */
  pierceArmor?: number;
  speed: number; // world units / sec
  visionRange: number;
  radius: number;
  cost: { food: number; wood: number; gold: number };
  buildTime: number; // seconds to train
  pop: number;
  trainedAt: string; // building def id
  age: number; // minimum age index required (0 = Dark)
  ranged: boolean;
  /** Extra damage vs an armor class — the rock-paper-scissors triangle. */
  bonus: Partial<Record<ArmorClass, number>>;
  /** Special role flags. */
  canGather?: boolean;
  canBuild?: boolean;
  canRepair?: boolean;
  healer?: boolean;
  aoeRadius?: number; // siege splash
  hero?: boolean; // unique, levels up in-match, respawns; one per player
  /** Only a realm that swore this Oath can train it (content/oaths.ts). */
  oath?: string;
  /**
   * Charge: the first blow after a run of at least `CHARGE_RUN` world units
   * deals this multiple of its damage. The Lancer's whole identity.
   */
  charge?: number;
  /** Stays hidden in woodland even while it shoots (the Ranger). */
  stalker?: boolean;
  /**
   * The shared unit whose place this one takes — a faction's Legionary is a
   * Man-at-Arms, an Oath's Lancer a Knight. Rarity you have unboxed for the
   * role carries over, so switching faction never strands your collection.
   */
  role?: string;
}

/** How far a charging unit must run before its next blow counts as a charge. */
export const CHARGE_RUN = 160;

const U = (d: UnitDef) => d;

export const UNITS: Record<string, UnitDef> = {
  villager: U({
    id: "villager",
    name: "Villager",
    desc: "Gathers food, wood and gold; builds structures. Defenseless in a real fight.",
    armorClass: ArmorClass.Villager,
    hp: 40,
    attack: 3,
    range: 0,
    attackInterval: 1.2,
    armor: 0,
    speed: 70,
    visionRange: 120,
    radius: 8,
    cost: { food: 50, wood: 0, gold: 0 },
    buildTime: 12,
    pop: 1,
    trainedAt: "town_center",
    age: 0,
    ranged: false,
    bonus: {},
    canGather: true,
    canBuild: true,
    canRepair: true,
  }),

  militia: U({
    id: "militia",
    name: "Man-at-Arms",
    desc: "Cheap, sturdy frontline infantry. Closes on archers; melts to massed cavalry.",
    armorClass: ArmorClass.Infantry,
    hp: 70,
    attack: 8,
    range: 0,
    attackInterval: 1.1,
    armor: 1,
    speed: 78,
    visionRange: 120,
    radius: 9,
    cost: { food: 60, wood: 0, gold: 20 },
    buildTime: 14,
    pop: 1,
    trainedAt: "barracks",
    age: 0,
    ranged: false,
    bonus: { [ArmorClass.Archer]: 4, [ArmorClass.Building]: 2 },
  }),

  spearman: U({
    id: "spearman",
    name: "Spearman",
    desc: "Anti-cavalry specialist. Brutal vs knights, weak against everything else.",
    armorClass: ArmorClass.Infantry,
    hp: 60,
    attack: 5,
    range: 0,
    attackInterval: 1.1,
    armor: 0,
    speed: 80,
    visionRange: 120,
    radius: 9,
    cost: { food: 35, wood: 25, gold: 0 },
    buildTime: 13,
    pop: 1,
    trainedAt: "barracks",
    age: 0,
    ranged: false,
    bonus: { [ArmorClass.Cavalry]: 25, [ArmorClass.Siege]: 5 },
  }),

  archer: U({
    id: "archer",
    name: "Archer",
    desc: "Ranged damage that shreds infantry. Fragile — keep it back, fear the cavalry.",
    armorClass: ArmorClass.Archer,
    hp: 38,
    attack: 6,
    range: 150,
    attackInterval: 1.4,
    armor: 0,
    speed: 80,
    visionRange: 170,
    radius: 8,
    cost: { food: 25, wood: 35, gold: 0 },
    buildTime: 16,
    pop: 1,
    trainedAt: "archery_range",
    age: 1,
    ranged: true,
    bonus: { [ArmorClass.Infantry]: 5 },
  }),

  skirmisher: U({
    id: "skirmisher",
    name: "Skirmisher",
    desc: "Cheap anti-archer ranged unit. Counters bowmen; poor against everything melee.",
    armorClass: ArmorClass.Archer,
    hp: 42,
    attack: 6,
    range: 130,
    attackInterval: 1.5,
    armor: 1,
    speed: 80,
    visionRange: 160,
    radius: 8,
    cost: { food: 35, wood: 35, gold: 0 },
    buildTime: 16,
    pop: 1,
    trainedAt: "archery_range",
    age: 1,
    ranged: true,
    bonus: { [ArmorClass.Archer]: 6 },
  }),

  horseman: U({
    id: "horseman",
    name: "Horseman",
    desc: "Light melee cavalry. Fast and cheap — charges down archers and siege, and arrives a whole age before the Knight. Spears gut it. (Banner Age)",
    armorClass: ArmorClass.Cavalry,
    hp: 80,
    attack: 9,
    range: 0,
    attackInterval: 1.1,
    armor: 1,
    pierceArmor: 1, // light barding shrugs a little arrow fire
    speed: 112,
    visionRange: 170,
    radius: 11,
    cost: { food: 70, wood: 35, gold: 0 },
    buildTime: 20,
    pop: 1,
    trainedAt: "stable",
    age: 1,
    ranged: false,
    bonus: { [ArmorClass.Archer]: 6, [ArmorClass.Siege]: 10 },
  }),

  shieldbearer: U({
    id: "shieldbearer",
    name: "Shieldbearer",
    desc: "A wall on legs. Hits softly, but soaks punishment that would fell anyone else. (Banner Age)",
    armorClass: ArmorClass.Infantry,
    hp: 95,
    attack: 4,
    range: 0,
    attackInterval: 1.2,
    armor: 3,
    pierceArmor: 5,
    speed: 72,
    visionRange: 120,
    radius: 9,
    cost: { food: 55, wood: 0, gold: 20 },
    buildTime: 17,
    pop: 1,
    trainedAt: "barracks",
    age: 1,
    ranged: false,
    bonus: { [ArmorClass.Building]: 2 },
    role: "militia",
  }),
  berserker: U({
    id: "berserker",
    name: "Berserker",
    desc: "All edge and no guard — the hardest-hitting foot soldier alive, for as long as he stays alive. (Crown Age)",
    armorClass: ArmorClass.Infantry,
    hp: 80,
    attack: 13,
    range: 0,
    attackInterval: 1.0,
    armor: 0,
    speed: 88,
    visionRange: 130,
    radius: 8,
    cost: { food: 70, wood: 0, gold: 45 },
    buildTime: 20,
    pop: 1,
    trainedAt: "barracks",
    age: 1, // the Jarls field them from the Banner Age
    ranged: false,
    bonus: { [ArmorClass.Archer]: 6, [ArmorClass.Villager]: 8 },
    role: "militia",
  }),
  longbow: U({
    id: "longbow",
    name: "Longbowman",
    desc: "Reaches further than anything else on two legs. Slow to draw, and helpless once caught. (Crown Age)",
    armorClass: ArmorClass.Archer,
    hp: 46,
    attack: 11,
    range: 215,
    attackInterval: 1.8,
    armor: 0,
    speed: 76,
    visionRange: 215,
    radius: 8,
    cost: { food: 20, wood: 32, gold: 18 },
    buildTime: 20,
    pop: 1,
    trainedAt: "archery_range",
    age: 2,
    ranged: true,
    bonus: { [ArmorClass.Infantry]: 7 },
  }),
  cataphract: U({
    id: "cataphract",
    name: "Cataphract",
    desc: "Horse and rider both in scale. Rolls through a line and barely notices the spears. (Crown Age)",
    armorClass: ArmorClass.Cavalry,
    hp: 150,
    attack: 13,
    range: 0,
    attackInterval: 1.3,
    armor: 2,
    pierceArmor: 5,
    speed: 104,
    visionRange: 150,
    radius: 10,
    cost: { food: 90, wood: 0, gold: 90 },
    buildTime: 28,
    pop: 1,
    trainedAt: "stable",
    age: 2,
    ranged: false,
    bonus: { [ArmorClass.Archer]: 8, [ArmorClass.Siege]: 6 },
    role: "knight",
  }),
  battlemage: U({
    id: "battlemage",
    name: "Battlemage",
    desc: "Calls down fire that scatters a packed formation. Frail, slow to cast, and worth guarding. (Crown Age)",
    armorClass: ArmorClass.Archer,
    hp: 58,
    attack: 20,
    range: 175,
    attackInterval: 2.6,
    armor: 0,
    speed: 74,
    visionRange: 175,
    radius: 8,
    cost: { food: 45, wood: 0, gold: 65 },
    buildTime: 26,
    pop: 1,
    trainedAt: "castle",
    age: 2,
    ranged: true,
    aoeRadius: 40,
    bonus: { [ArmorClass.Infantry]: 8 },
  }),
  bombard: U({
    id: "bombard",
    name: "Bombard",
    desc: "A siege gun on a carriage. Flattens buildings and anything unlucky enough to be near them. (Empire Age)",
    armorClass: ArmorClass.Siege,
    hp: 110,
    attack: 40,
    range: 230,
    attackInterval: 4.2,
    armor: 1,
    speed: 52,
    visionRange: 210,
    radius: 11,
    cost: { food: 0, wood: 140, gold: 140 },
    buildTime: 44,
    pop: 2,
    trainedAt: "siege_workshop",
    age: 3,
    ranged: true,
    aoeRadius: 52,
    bonus: { [ArmorClass.Building]: 55, [ArmorClass.Infantry]: 10 },
  }),
  crossbow: U({
    id: "crossbow",
    name: "Crossbowman",
    desc: "Heavy ranged punch. Outranges and outshoots the Archer; the backbone of a Crown-age line. (Crown Age)",
    armorClass: ArmorClass.Archer,
    hp: 45,
    attack: 9,
    range: 170,
    attackInterval: 1.5,
    armor: 1,
    speed: 78,
    visionRange: 180,
    radius: 8,
    cost: { food: 0, wood: 25, gold: 55 },
    buildTime: 18,
    pop: 1,
    trainedAt: "archery_range",
    age: 2,
    ranged: true,
    bonus: { [ArmorClass.Infantry]: 9 },
  }),

  knight: U({
    id: "knight",
    name: "Knight",
    desc: "Fast, heavy cavalry. Runs down archers, siege and villagers. Hates spears.",
    armorClass: ArmorClass.Cavalry,
    hp: 130,
    attack: 12,
    range: 0,
    attackInterval: 1.2,
    armor: 1,
    speed: 115,
    visionRange: 130,
    radius: 11,
    cost: { food: 70, wood: 0, gold: 75 },
    buildTime: 20,
    pop: 1,
    trainedAt: "stable",
    age: 2,
    ranged: false,
    bonus: { [ArmorClass.Archer]: 6, [ArmorClass.Siege]: 8, [ArmorClass.Villager]: 6 },
  }),

  catapult: U({
    id: "catapult",
    name: "Catapult",
    desc: "Long-range siege. Devastates buildings and tight formations; helpless up close.",
    armorClass: ArmorClass.Siege,
    hp: 90,
    attack: 24,
    range: 200,
    attackInterval: 3.2,
    armor: 1,
    speed: 45,
    visionRange: 180,
    radius: 12,
    cost: { food: 0, wood: 160, gold: 80 },
    buildTime: 30,
    pop: 2,
    trainedAt: "siege_workshop",
    age: 2,
    ranged: true,
    aoeRadius: 36,
    bonus: { [ArmorClass.Building]: 40, [ArmorClass.Infantry]: 8, [ArmorClass.Archer]: 8 },
  }),

  ram: U({
    id: "ram",
    name: "Battering Ram",
    desc: "Armored siege engine built to break walls and buildings. Slow and clumsy vs troops.",
    armorClass: ArmorClass.Siege,
    hp: 200,
    attack: 6,
    range: 0,
    attackInterval: 2.5,
    armor: 3,
    speed: 50,
    visionRange: 120,
    radius: 13,
    cost: { food: 0, wood: 160, gold: 40 },
    buildTime: 28,
    pop: 2,
    trainedAt: "siege_workshop",
    age: 2,
    ranged: false,
    bonus: { [ArmorClass.Building]: 50 },
  }),

  trade_cart: U({
    id: "trade_cart",
    name: "Trade Cart",
    desc: "Runs gold between two of your Markets, or an ally's. Pays by distance — a long, well-guarded route is a second economy. Unarmed.",
    armorClass: ArmorClass.Siege, // a cart, not a soldier: siege armour class, no attack
    hp: 140,
    attack: 0,
    range: 0,
    attackInterval: 1,
    armor: 0,
    pierceArmor: 2,
    speed: 74,
    visionRange: 140,
    radius: 10,
    cost: { food: 0, wood: 100, gold: 50 },
    buildTime: 22,
    pop: 1,
    trainedAt: "market",
    age: 1,
    ranged: false,
    bonus: {},
  }),

  hero: U({
    id: "hero",
    name: "Champion",
    desc: "Your unique hero. Towering in a fight, grows stronger with every kill, and rises again at your Town Center if he falls.",
    armorClass: ArmorClass.Infantry,
    hp: 230,
    attack: 12,
    range: 0,
    attackInterval: 1.0,
    armor: 1,
    speed: 96,
    visionRange: 190,
    radius: 12,
    cost: { food: 150, wood: 0, gold: 120 },
    buildTime: 35,
    pop: 3,
    trainedAt: "town_center",
    age: 0,
    ranged: false,
    hero: true,
    bonus: { [ArmorClass.Archer]: 3, [ArmorClass.Siege]: 4, [ArmorClass.Cavalry]: 4, [ArmorClass.Building]: 3 },
  }),

  trebuchet: U({
    id: "trebuchet",
    name: "Trebuchet",
    desc: "Siege artillery with colossal range. Levels walls and towers from beyond their reach — but glacially slow and helpless up close. (Empire Age)",
    armorClass: ArmorClass.Siege,
    hp: 120,
    attack: 55,
    range: 340,
    attackInterval: 4.6,
    armor: 1,
    speed: 34,
    visionRange: 220,
    radius: 13,
    cost: { food: 0, wood: 200, gold: 200 },
    buildTime: 40,
    pop: 3,
    trainedAt: "siege_workshop",
    age: 3,
    ranged: true,
    aoeRadius: 30,
    bonus: { [ArmorClass.Building]: 110, [ArmorClass.Siege]: 20 },
  }),

  monk: U({
    id: "monk",
    name: "Monk",
    desc: "Crown-age support. Heals nearby allies over time. No frontline value.",
    armorClass: ArmorClass.Infantry,
    hp: 45,
    attack: 0,
    range: 0,
    attackInterval: 1,
    armor: 0,
    speed: 70,
    visionRange: 150,
    radius: 8,
    cost: { food: 0, wood: 0, gold: 100 },
    buildTime: 24,
    pop: 1,
    trainedAt: "castle",
    age: 2,
    ranged: false,
    healer: true,
    bonus: {},
  }),

  javelin: U({
    id: "javelin",
    name: "Javelin Thrower",
    desc: "Hurls heavy javelins — hits harder than an archer but at shorter range. Punishes cavalry that close on it. (Banner Age)",
    armorClass: ArmorClass.Archer,
    hp: 48,
    attack: 9,
    range: 105,
    attackInterval: 1.6,
    armor: 1,
    speed: 84,
    visionRange: 150,
    radius: 8,
    cost: { food: 40, wood: 0, gold: 30 },
    buildTime: 17,
    pop: 1,
    trainedAt: "archery_range",
    age: 1,
    ranged: true,
    bonus: { [ArmorClass.Cavalry]: 8 },
  }),

  handcannon: U({
    id: "handcannon",
    name: "Hand Cannoneer",
    desc: "Gunpowder marksman. Enormous range and a punishing shot, but reloads slowly — devastating massed, helpless if rushed. (Empire Age)",
    armorClass: ArmorClass.Archer,
    hp: 58,
    attack: 22,
    range: 195,
    attackInterval: 2.5,
    armor: 1,
    speed: 76,
    visionRange: 200,
    radius: 8,
    cost: { food: 0, wood: 30, gold: 70 },
    buildTime: 22,
    pop: 1,
    trainedAt: "archery_range",
    age: 3,
    ranged: true,
    bonus: { [ArmorClass.Infantry]: 14 },
  }),

  raider: U({
    id: "raider",
    name: "Raider",
    desc: "Light, lightning-fast cavalry built to butcher villagers and wreck an economy. Fragile in a real fight — strike and run. (Banner Age)",
    armorClass: ArmorClass.Cavalry,
    hp: 55,
    attack: 7,
    range: 0,
    attackInterval: 1.0,
    armor: 0,
    speed: 135,
    visionRange: 140,
    radius: 10,
    cost: { food: 60, wood: 0, gold: 15 },
    buildTime: 18,
    pop: 1,
    trainedAt: "stable",
    age: 1,
    ranged: false,
    bonus: { [ArmorClass.Villager]: 14 },
  }),

  scout: U({
    id: "scout",
    name: "Scout",
    desc: "A swift outrider with keen eyes. Cheap early scouting and light harassment — no match for real soldiers.",
    armorClass: ArmorClass.Cavalry,
    hp: 45,
    attack: 3,
    range: 0,
    attackInterval: 1.3,
    armor: 0,
    speed: 132,
    visionRange: 230,
    radius: 10,
    cost: { food: 65, wood: 0, gold: 0 },
    buildTime: 15,
    pop: 1,
    trainedAt: "town_center",
    age: 0,
    ranged: false,
    bonus: {},
  }),

  twohand: U({
    id: "twohand",
    name: "Two-Handed Swordsman",
    desc: "Elite heavy infantry with a greatsword — the top of the foot-soldier line. Cleaves infantry and buildings; still wary of massed cavalry. (Crown Age)",
    armorClass: ArmorClass.Infantry,
    hp: 95,
    attack: 12,
    range: 0,
    attackInterval: 1.1,
    armor: 1,
    speed: 80,
    visionRange: 120,
    radius: 9,
    cost: { food: 70, wood: 0, gold: 60 },
    buildTime: 16,
    pop: 1,
    trainedAt: "barracks",
    age: 2,
    ranged: false,
    bonus: { [ArmorClass.Archer]: 4, [ArmorClass.Building]: 4 },
  }),

  king: U({
    id: "king",
    name: "King",
    desc: "Your sovereign. In Regicide, protect your King and slay the enemy's to win. Sturdy and brave, but losing him loses the game.",
    armorClass: ArmorClass.Infantry,
    hp: 250,
    attack: 10,
    range: 0,
    attackInterval: 1.2,
    armor: 2,
    speed: 90,
    visionRange: 160,
    radius: 11,
    cost: { food: 0, wood: 0, gold: 0 },
    buildTime: 1,
    pop: 0,
    trainedAt: "", // never trained — spawned at match start in Regicide
    age: 0,
    ranged: false,
    bonus: {},
  }),

  pikeman: U({
    id: "pikeman",
    name: "Pikeman",
    desc: "A disciplined pike block — even deadlier to cavalry than the spearman, and it keeps spears relevant against Crown-age knights. (Crown Age)",
    armorClass: ArmorClass.Infantry,
    hp: 75,
    attack: 6,
    range: 0,
    attackInterval: 1.1,
    armor: 1,
    speed: 80,
    visionRange: 120,
    radius: 9,
    cost: { food: 50, wood: 25, gold: 0 },
    buildTime: 14,
    pop: 1,
    trainedAt: "barracks",
    age: 2,
    ranged: false,
    bonus: { [ArmorClass.Cavalry]: 38, [ArmorClass.Siege]: 8 },
  }),

  // ------------------------------------------------------------------------
  // Oath units. Each is trainable only by a realm that swore its Oath — the
  // signature a civilisation's unique unit would be, earned mid-match instead
  // of picked before it.

  sworn_blade: U({
    id: "sworn_blade",
    name: "Sworn Blade",
    desc: "Oath of the Sword. Quick, hard-hitting swordsmen who arrive an age before the Two-Handed — built to strike an enemy before it is ready. (Banner Age)",
    armorClass: ArmorClass.Infantry,
    hp: 74,
    attack: 10,
    range: 0,
    attackInterval: 1.0,
    armor: 1,
    speed: 90,
    visionRange: 125,
    radius: 9,
    cost: { food: 60, wood: 0, gold: 35 },
    buildTime: 15,
    pop: 1,
    trainedAt: "barracks",
    age: 1,
    ranged: false,
    bonus: { [ArmorClass.Archer]: 5, [ArmorClass.Villager]: 5, [ArmorClass.Building]: 3 },
    oath: "sword",
    role: "militia",
  }),

  lancer: U({
    id: "lancer",
    name: "Lancer",
    desc: "Oath of the Lance. Heavy horse with a couched lance: the first blow after a run hits three times as hard. Let it ride in; don't let it stand and trade. (Crown Age)",
    armorClass: ArmorClass.Cavalry,
    hp: 120,
    attack: 11,
    range: 0,
    attackInterval: 1.3,
    armor: 1,
    pierceArmor: 2,
    speed: 122,
    visionRange: 150,
    radius: 13,
    cost: { food: 80, wood: 0, gold: 70 },
    buildTime: 22,
    pop: 1,
    trainedAt: "stable",
    age: 2,
    ranged: false,
    bonus: { [ArmorClass.Archer]: 6, [ArmorClass.Siege]: 8 },
    oath: "lance",
    charge: 3,
    role: "knight",
  }),

  ranger: U({
    id: "ranger",
    name: "Ranger",
    desc: "Oath of the Bow. A woodland archer who stays hidden among the trees even while shooting — an ambush that doesn't give itself away. (Crown Age)",
    armorClass: ArmorClass.Archer,
    hp: 45,
    attack: 9,
    range: 185,
    attackInterval: 1.5,
    armor: 0,
    pierceArmor: 1,
    speed: 84,
    visionRange: 200,
    radius: 9,
    cost: { food: 25, wood: 40, gold: 15 },
    buildTime: 18,
    pop: 1,
    trainedAt: "archery_range",
    age: 2,
    ranged: true,
    bonus: { [ArmorClass.Infantry]: 8 },
    oath: "bow",
    stalker: true,
    role: "archer",
  }),

  halberdier: U({
    id: "halberdier",
    name: "Halberdier",
    desc: "Oath of the Shield. Pike and axe on one haft: murderous to cavalry, and it chops rams apart. Slow, and no match for swords. (Crown Age)",
    armorClass: ArmorClass.Infantry,
    hp: 85,
    attack: 8,
    range: 0,
    attackInterval: 1.2,
    armor: 2,
    pierceArmor: 1,
    speed: 76,
    visionRange: 120,
    radius: 9,
    cost: { food: 55, wood: 35, gold: 0 },
    buildTime: 15,
    pop: 1,
    trainedAt: "barracks",
    age: 2,
    ranged: false,
    bonus: { [ArmorClass.Cavalry]: 40, [ArmorClass.Siege]: 22, [ArmorClass.Building]: 2 },
    oath: "shield",
    role: "pikeman",
  }),

  great_bombard: U({
    id: "great_bombard",
    name: "Great Bombard",
    desc: "Oath of the Engine. A cannon too big for a carriage, dragged into place and fired from beyond any tower's reach. Painfully slow; guard it. (Empire Age)",
    armorClass: ArmorClass.Siege,
    hp: 160,
    attack: 60,
    range: 300,
    attackInterval: 5.0,
    armor: 2,
    speed: 38,
    visionRange: 220,
    radius: 15,
    cost: { food: 0, wood: 220, gold: 240 },
    buildTime: 50,
    pop: 3,
    trainedAt: "siege_workshop",
    age: 3,
    ranged: true,
    bonus: { [ArmorClass.Building]: 90, [ArmorClass.Infantry]: 12 },
    aoeRadius: 60,
    oath: "engine",
    role: "trebuchet",
  }),

  royal_guard: U({
    id: "royal_guard",
    name: "Royal Guard",
    desc: "Oath of the Crown. Plate-clad household troops — the toughest foot soldiers in the realm, and good against almost anything that isn't massed siege. (Empire Age)",
    armorClass: ArmorClass.Infantry,
    hp: 150,
    attack: 15,
    range: 0,
    attackInterval: 1.1,
    armor: 3,
    pierceArmor: 4,
    speed: 80,
    visionRange: 130,
    radius: 10,
    cost: { food: 90, wood: 0, gold: 90 },
    buildTime: 24,
    pop: 1,
    trainedAt: "castle",
    age: 3,
    ranged: false,
    bonus: { [ArmorClass.Archer]: 6, [ArmorClass.Cavalry]: 8, [ArmorClass.Building]: 4 },
    oath: "crown",
    role: "twohand",
  }),

  // ------------------------------------------------------------------------
  // Faction units (content/factions.ts). Each takes a shared unit's place in
  // its faction's roster, or joins it; `role` says whose rarity it inherits.

  yeoman: U({
    id: "yeoman",
    name: "Longbowman",
    desc: "The Kingdom. Outranges every archer in the field; slow to draw and no good up close. (Crown Age)",
    armorClass: ArmorClass.Archer,
    hp: 45,
    attack: 10,
    range: 205,
    attackInterval: 1.8,
    armor: 0,
    speed: 76,
    visionRange: 215,
    radius: 8,
    cost: { food: 0, wood: 40, gold: 30 },
    buildTime: 20,
    pop: 1,
    trainedAt: "archery_range",
    age: 2,
    ranged: true,
    bonus: { [ArmorClass.Infantry]: 7 },
    role: "archer",
  }),

  legionary: U({
    id: "legionary",
    name: "Legionary",
    desc: "The Legion. Takes the Man-at-Arms' place: a tall shield that turns arrows, and the discipline to hold. A touch slower.",
    armorClass: ArmorClass.Infantry,
    hp: 72,
    attack: 8,
    range: 0,
    attackInterval: 1.1,
    armor: 1,
    pierceArmor: 2,
    speed: 75,
    visionRange: 120,
    radius: 9,
    cost: { food: 60, wood: 0, gold: 30 },
    buildTime: 14,
    pop: 1,
    trainedAt: "barracks",
    age: 0,
    ranged: false,
    bonus: { [ArmorClass.Archer]: 4, [ArmorClass.Building]: 3 },
    role: "militia",
  }),

  samurai: U({
    id: "samurai",
    name: "Samurai",
    desc: "The Shogunate. Takes the Two-Handed Swordsman's place: better armoured and quicker with the blade, and priced like it. (Crown Age)",
    armorClass: ArmorClass.Infantry,
    hp: 100,
    attack: 12,
    range: 0,
    attackInterval: 0.95,
    armor: 2,
    speed: 82,
    visionRange: 130,
    radius: 9,
    cost: { food: 70, wood: 0, gold: 65 },
    buildTime: 18,
    pop: 1,
    trainedAt: "barracks",
    age: 2,
    ranged: false,
    bonus: { [ArmorClass.Archer]: 4, [ArmorClass.Building]: 3 },
    role: "twohand",
  }),

  horse_archer: U({
    id: "horse_archer",
    name: "Horse Archer",
    desc: "The Khanate. Shoots from the saddle and never stops moving — hard to catch, fragile if you do. (Banner Age)",
    armorClass: ArmorClass.Cavalry,
    hp: 65,
    attack: 8,
    range: 140,
    attackInterval: 1.5,
    armor: 0,
    pierceArmor: 1,
    speed: 116,
    visionRange: 190,
    radius: 12,
    cost: { food: 35, wood: 0, gold: 40 },
    buildTime: 22,
    pop: 1,
    trainedAt: "archery_range",
    age: 1,
    ranged: true,
    bonus: { [ArmorClass.Infantry]: 2 },
    role: "archer",
  }),

  pulse_trooper: U({
    id: "pulse_trooper",
    name: "Pulse Trooper",
    desc: "The Ascendancy. Takes the Crossbowman's place: an energy rifle with a flat, punishing shot. Costly, as everything of theirs is. (Crown Age)",
    armorClass: ArmorClass.Archer,
    hp: 50,
    attack: 10,
    range: 175,
    attackInterval: 1.5,
    armor: 1,
    pierceArmor: 2,
    speed: 78,
    visionRange: 200,
    radius: 9,
    cost: { food: 10, wood: 25, gold: 55 },
    buildTime: 18,
    pop: 1,
    trainedAt: "archery_range",
    age: 2,
    ranged: true,
    bonus: { [ArmorClass.Infantry]: 8, [ArmorClass.Cavalry]: 3 },
    role: "crossbow",
  }),

  skimmer: U({
    id: "skimmer",
    name: "Skimmer",
    desc: "The Ascendancy. Takes the Horseman's place: a hover-sled rider, the fastest thing on the field — a raider and a siege-hunter. (Banner Age)",
    armorClass: ArmorClass.Cavalry,
    hp: 75,
    attack: 9,
    range: 0,
    attackInterval: 1.1,
    armor: 1,
    pierceArmor: 2,
    speed: 126,
    visionRange: 170,
    radius: 12,
    cost: { food: 70, wood: 0, gold: 30 },
    buildTime: 20,
    pop: 1,
    trainedAt: "stable",
    age: 1,
    ranged: false,
    bonus: { [ArmorClass.Archer]: 6, [ArmorClass.Siege]: 10 },
    role: "horseman",
  }),
};

export const UNIT_IDS = Object.keys(UNITS);
