package com.jrpetty.mobtrumps;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

/**
 * The mod's own audio.
 *
 * <p>Everything used to borrow a vanilla sample — a button click for a card, a
 * note block for a win. Those carry Minecraft's associations rather than the
 * table's, and a UI cue that plays hundreds of times a session is the one place
 * where borrowed audio is most obvious.
 *
 * <p>The samples are generated by {@code tools/gensounds.py} and held to hard
 * limits by {@code tools/checksounds.py}: quiet, soft-edged, and with nothing
 * in the 8-16kHz band that makes a sound harsh rather than loud. They are meant
 * to sit under the game, not on top of it.
 */
public final class ModSounds {

    public static final DeferredRegister<SoundEvent> SOUNDS =
            DeferredRegister.create(Registries.SOUND_EVENT, MobTrumps.MODID);

    /** One card turning over. */
    public static final DeferredHolder<SoundEvent, SoundEvent> CARD_FLIP = register("card_flip");
    /** A card set down on the felt — softer and lower than a flip. */
    public static final DeferredHolder<SoundEvent, SoundEvent> CARD_PLACE = register("card_place");
    /** A deck being riffled. */
    public static final DeferredHolder<SoundEvent, SoundEvent> SHUFFLE = register("shuffle");
    /** A pack being torn open. */
    public static final DeferredHolder<SoundEvent, SoundEvent> PACK_RIP = register("pack_rip");
    /** A holo catching the light — for a foil pull. */
    public static final DeferredHolder<SoundEvent, SoundEvent> FOIL_SHIMMER = register("foil_shimmer");
    /** A wager settling: the wooden knock that says the price is agreed. */
    public static final DeferredHolder<SoundEvent, SoundEvent> GAVEL = register("gavel");
    /** A single fragment landing — the small click behind a stake or a bid. */
    public static final DeferredHolder<SoundEvent, SoundEvent> CHIP = register("chip");

    private static DeferredHolder<SoundEvent, SoundEvent> register(String name) {
        ResourceLocation id = ResourceLocation.fromNamespaceAndPath(MobTrumps.MODID, name);
        return SOUNDS.register(name, () -> SoundEvent.createVariableRangeEvent(id));
    }

    private ModSounds() {
    }
}
