org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.93
neo_version_range=[21.1,)
loader_version_range=[4,)

mod_id=gadgets
mod_name=Gadgets
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.gadgets
mod_authors=jrpetty
mod_description=A few handy gadgets: Rope Arrow, Light Arrow, Player Sensor, and Filter Hopper.
