org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.93
neo_version_range=[21.1,)
loader_version_range=[4,)

mod_id=cartoonhero
mod_name=Cartoon Hero
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.cartoonhero
mod_authors=jrpetty
mod_description=Become a cartoon hero! Adds the Hero Emblem and glowing Cartoon Bricks.
