plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = mod_version
group = 'com.jrpetty.mobtrumps'

base {
    archivesName = 'mobtrumps'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

neoForge {
    version = neoforge_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        mobtrumps {
            sourceSet sourceSets.main
        }
    }
}

processResources {
    var replacements = [mod_version: mod_version]
    inputs.properties replacements
    filesMatching('META-INF/neoforge.mods.toml') {
        expand replacements
    }
}
